
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'warehouse_bot/version'

Gem::Specification.new do |spec|
  spec.name          = 'warehouse_bot'
  spec.version       = WarehouseBot::VERSION
  spec.authors       = ['peter.bell215']
  spec.email         = ['peter.bell215@gmail.com']

  spec.summary       = 'Provide a way of caching database data generated by FactoryGirl or similar'
  spec.description   = %(
    As RSpec runs, this tracks how test data is generated.  So if some test data has been previously generated for
    another test, then the Gem will spot this, and load the data from YAML filespec.  If not, it will allow the test
    data to be generated, and then save it as YAML to a cache.)
  spec.homepage      = 'https://github.com/peterbell215/warehouse_bot'
  spec.license       = 'MIT'


  # Prevent pushing this gem to RubyGems.org. To allow pushes either set the 'allowed_push_host'
  # to allow pushing to a single host or delete this section to allow pushing to any host.
  if spec.respond_to?(:metadata)
    spec.metadata['allowed_push_host'] = "TODO: Set to 'http://mygemserver.com'"
  else
    raise 'RubyGems 2.0 or newer is required to protect against public gem pushes.'
  end

  spec.files         = `git ls-files -z`.split("\x0").reject do |f|
    f.match(%r{^(test|spec|features)/})
  end
  spec.bindir        = 'exe'
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ['lib']

  spec.add_dependency 'activerecord', '~> 5.1'
  spec.add_dependency 'activesupport', '~> 5.1'
  spec.add_dependency 'activerecord-import'
  spec.add_dependency 'factory_bot', '~> 4.8'

  spec.add_development_dependency 'bundler', '~> 1.16'
  spec.add_development_dependency 'rake', '~> 10.0'
  spec.add_development_dependency 'rspec', '~> 3.0'
  spec.add_development_dependency 'rubocop-rspec'
  spec.add_development_dependency 'faker'
  spec.add_development_dependency 'database_cleaner'
  spec.add_development_dependency 'sqlite3'
  spec.add_development_dependency 'yard'
end
